services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./.env
      - ./.env.auth
      - ./.env.atlas
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
  websocket:
    build: ./websocket
    container_name: websocket
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: ./websocket
        target: /websocket
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis:
